### ISSUE TITLE
Implement getOS function

### ISSUE THREAD

**Issue by pooki3bear** [moloch--/sliver-script#2]
My javascript is poor, but it does not look like there is a interactivesession method to retrieve the operating system details directly. Instead I am using `event.getSession().array[7]`

**Comment by moloch--** [comment]
The way to get this is to call `session.getOs();` on the protobuf Session object (not the interactive session object), the name `getOs` is a little weird, but that's because it's auto-generated by gRPC / protobuf

**Comment by pooki3bear** [comment]
Thanks!
