### ISSUE TITLE
Vue can not use it.

### ISSUE THREAD

**Issue by RedTeamWing** [moloch--/sliver-script#3]
It cannot be used in Vue, and may require grpc-web

![image](https://user-images.githubusercontent.com/25416365/126794609-e3ae8338-5a48-4e63-a809-ec71b9ea17e9.png)
dns and http2 cannot be installed. I want to use Vue to make  sliver's GUI. QAQ

**Comment by RedTeamWing** [comment]
![image](https://user-images.githubusercontent.com/25416365/126794880-e8ce2404-7038-4c11-b665-45fe3bc7efac.png)

**Comment by moloch--** [comment]
That is correct, `sliver-script` is a NodeJS module and cannot be used in the browser directly.

**Comment by moloch--** [comment]
If you want to use Vue to create a GUI you'll need to implement a server component that bridges `sliver-script` with something like [ExpressJS](https://expressjs.com/)

**Comment by RedTeamWing** [comment]
Whether to consider replacing grpc with grpc web so that browsers can use it。

**Comment by moloch--** [comment]
`grpc-web` requires too many changes and does lacks certain functionality that is needed in `sliver-script` (such as the ability to do TCP connections/etc.

However, you can create your own fork of `sliver-script` that uses `grpc-web`
